include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - .history/**
    - lib/helpers/route.dart
linter:
  rules:
    - always_put_required_named_parameters_first
    - file_names
    - library_names
    - library_prefixes
    - avoid_annotating_with_dynamic
    - avoid_catching_errors
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_slow_async_io
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - comment_references
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    #    - lines_longer_than_80_chars # under review (see #1068)
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - non_constant_identifier_names
    - constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors_in_immutables
    - prefer_constructors_over_static_methods
    - prefer_final_fields
    - prefer_foreach
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_void_to_null
    - provide_deprecation_message
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks