include: package:flutter_lints/flutter.yaml
# https://dart.dev/tools/linter-rules
analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    # ignore vscode .history files
    - .history/**
    - lib/helpers/route.dart
linter:
  rules:
    #    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    #    - always_specify_types
    - avoid_annotating_with_dynamic
    #    - avoid_as
    #    - avoid_bool_literals_in_conditional_expressions # under review (see #1068)
    # - avoid_catches_without_on_clauses
    - avoid_catching_errors
    #    - avoid_classes_with_only_static_members
    #    - avoid_double_and_int_checks # under review (see #1068)
    #    - avoid_field_initializers_in_const_classes # under review (see #1068)
    #    - avoid_function_literals_in_foreach_calls
    #    - avoid_implementing_value_types
    #    - avoid_js_rounded_ints # under review (see #1068)
    - avoid_positional_boolean_parameters
    #    - avoid_private_typedef_functions # under review (see #1068)
    - avoid_redundant_argument_values
    #    - avoid_renaming_method_parameters # under review (see #1068)
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_setters_without_getters
    #    - avoid_single_cascade_in_expression_statements # under review (see #1068)
    - avoid_slow_async_io
    #    - avoid_types_on_closure_parameters
    #    - avoid_unused_constructor_parameters # under review (see #1068)
    #    - avoid_void_async # under review (see #1068)
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    #    - cascade_invocations
    #    - close_sinks # https://github.com/dart-lang/linter/issues/268
    - comment_references
    #    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - file_names # under review (see #1068)
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - lines_longer_than_80_chars # under review (see #1068)
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    #    - non_constant_identifier_names
    #    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    #    - prefer_bool_in_asserts # Deprecated
    #    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    #    - prefer_const_declarations # under review (see #1068)
    #    - prefer_const_literals_to_create_immutables # under review (see #1068)
    - prefer_constructors_over_static_methods
#    - prefer_expression_function_bodies
    - prefer_final_fields
    #    - prefer_final_locals
    - prefer_foreach
    #    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    #    - prefer_mixin
    - prefer_null_aware_operators
#    - prefer_relative_imports
    #    - prefer_typing_uninitialized_variables # under review (see #1068)
    - prefer_void_to_null
    - provide_deprecation_message
    #    - public_member_api_docs
    #    - sort_constructors_first
    #    - sort_unnamed_constructors_first
    #    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    #    - type_annotate_public_apis
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks